set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_large_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_logo_data.c
  ${CMAKE_CURRENT_LIST_DIR}/lv_example_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/lv_example.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_arc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_buttonmatrix_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_calendar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_checkbox_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_dropdown_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_gif_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_image_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_imagebutton_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_keyboard_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_led_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_line_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_obj_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_qrcode_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_roller_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_scale_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_spangroup_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_spinbox_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_spinner_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_table_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_tabview_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/lv_example_textarea_gen.c)