name: Pull Request Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  pr-check:
    runs-on: ubuntu-latest
    env:
      LVGL_CLI_TOKEN: ${{ secrets.LVGL_CLI_TOKEN }}

    steps:
      - name: Check token
        env:
          LVGL_CLI_TOKEN: ${{ secrets.LVGL_CLI_TOKEN }}
        run: |
          if [ -z "$LVGL_CLI_TOKEN" ]; then
            echo "LVGL_CLI_TOKEN is not set. Skipping..."
            exit 0
          fi

      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.13.0"

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.6

      - name: Remove Generated Files
        run: find examples -path examples/images -prune -o -type f \( -name '*.c' -o -name '*.h' \) -print | xargs rm -f

      - name: Download CLI
        run: curl -L https://github.com/lvgl/lvgl_editor/releases/download/v2.0.0/LVGL_Pro_CLI-2.0.0-linux.zip -o lvgl-cli.zip

      - name: Unzip CLI
        run: unzip lvgl-cli.zip -d lvgl-cli

      - name: Generate Code
        run: |
          node ./lvgl-cli/lved-cli.js generate examples

      - name: Compile Code
        run: |
          node ./lvgl-cli/lved-cli.js compile examples --target cli

      - name: Run tests
        run: |
          node ./lvgl-cli/lved-cli.js run-all-tests examples
